### PR TITLE
Added ping check feature to Slmod

### PR DESCRIPTION
**Pull request by flurreh**
Added ping check feature to Slmod which autokicks players who exceed a configured ping limit

### CODE REVIEW

**Comment by mvee** [comment]
Good addition! Maybe option to disable warnings?

**Comment by flurreh** [comment]
Are you talking about disabling just the warning message or rather kicking the player directly after the first high ping detection? For the latter you could set `pingcheck_conf.warning_limit` to zero. If the first is what you want, I can add a configuration option for that.

**Comment by mvee** [comment]
Ah yeah, the first one. Maybe so that it is still logged.

**Comment by flurreh** [comment]
I've added this feature. Now the warning message can be disabled by setting the `pingcheck_conf.warning_msg` variable to false.

**Pull request merged**
